### ISSUE TITLE
how can I solve this error when installing podsixnet?

### ISSUE THREAD

**Issue by pauliyobo** [chr15m/PodSixNet#12]
Hi. I've tried different times to install podsixnet with pip but the error that i get is:

Using cached PodSixNet-0.9.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-build-_t947scg\podsixnet\set
up.py", line 14, in <module>
        version=subprocess.check_output(["git", "describe", "--tag"]).decode().s
trip(),
      File "c:\users\user\appdata\local\programs\python\python36-32\lib\subpr
ocess.py", line 336, in check_output
        **kwargs).stdout
      File "c:\users\user\appdata\local\programs\python\python36-32\lib\subpr
ocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tag']' return
ed non-zero exit status 128.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\
AppData\Local\Temp\pip-build-_t947scg\podsixnet\
I've tried from the source by clonying it, but it's still the same.

**Comment by chr15m** [comment]
@pauliyobo this should be fixed now. Can you test it and let me know?

**Comment by pauliyobo** [comment]
I still have that error

2018-01-30 9:24 GMT+01:00, Chris McCormick <notifications@github.com>:

**Comment by hjpotter92** [comment]
The same is happening when I try to install the package using either `pip` or `easy_install`. There is no difference when I use either python 2.7 or 3.6 @chr15m 

## Python 2.7 traceback:
```
$ pip install podsixnet
Collecting podsixnet
  Using cached PodSixNet-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\hjpott~1\appdata\local\temp\pip-build-8ny46c\podsixnet\setup.py", line 14, in <module>
        version=subprocess.check_output(["git", "describe", "--tag", "--always"]).decode().strip(),
      File "c:\program files\python\lib\subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tag', '--always']' returned non-zero exit status 128

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\hjpott~1\appdata\local\temp\pip-build-8ny46c\podsixnet\
```

## Python 3.6 traceback

```
$ pip install podsixnet
Collecting podsixnet
  Using cached PodSixNet-0.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\HJPOTT~1\AppData\Local\Temp\pip-build-5nq253r5\podsixnet\setup.py", line 14, in <module>
        version=subprocess.check_output(["git", "describe", "--tag", "--always"]).decode().strip(),
      File "c:\program files\python3.6\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "c:\program files\python3.6\lib\subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tag', '--always']' returned non-zero exit status 128.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\HJPOTT~1\AppData\Local\Temp\pip-build-5nq253r5\podsixnet\
```

The `easy_install` had a slightly longer stacktrace:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python3.6\Scripts\easy_install.exe\__main__.py", line 9, in <module>
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 2265, in main
    **kw
  File "c:\program files\python3.6\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "c:\program files\python3.6\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "c:\program files\python3.6\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 876, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 1115, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "c:\program files\python3.6\lib\site-packages\setuptools\command\easy_install.py", line 1101, in run_setup
    run_setup(setup_script, args)
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 251, in run_setup
    raise
  File "c:\program files\python3.6\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "c:\program files\python3.6\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 144, in resume
    six.reraise(type, exc, self._tb)
  File "c:\program files\python3.6\lib\site-packages\pkg_resources\_vendor\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 157, in save_modules
    yield saved
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 198, in setup_context
    yield
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 248, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 278, in run
    return func()
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 246, in runner
    _execfile(setup_script, ns)
  File "c:\program files\python3.6\lib\site-packages\setuptools\sandbox.py", line 47, in _execfile
    exec(code, globals, locals)
  File "C:\Users\HJPOTT~1\AppData\Local\Temp\easy_install-00ahp3gk\PodSixNet-0.9.3\setup.py", line 14, in <module>
  File "c:\program files\python3.6\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "c:\program files\python3.6\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'describe', '--tag', '--always']' returned non-zero exit status 128.
```

**Comment by chr15m** [comment]
@pauliyobo @hjpotter92 this should be fixed now in `0.9.4`.
